# Conda packages for my base environment.
#
# mamba install --file environment.yml
# conda install --file environment.yml
#
black
flake8
ipython
isort
mypy
pip
pycodestyle
pydocstyle
pylint
pytest
sphinx
