#!/usr/bin/env zsh

# ==== aliases ==== #

if (( $+commands[bat] )); then
  alias cat=bat
fi
alias chown='chown -R'
alias cp='cp -i -r'
alias diff=colordiff
alias d='dirs -v | head -10'
alias df='df -H'
alias dot='cd ~/repos/dotfiles'
alias du='du -hs'
alias dus='\du -d 1 -h | sort -h'
alias e=exit
alias finder='open -a Finder .'
alias grep='grep --color=auto --exclude-dir={.git,.hg,.svn}'
alias h='fc -l'
alias history='fc -l 1 | less'
alias info='info --vi-keys'
alias j='jobs -l'
alias lsd='ls -l -d -- *(/)'
alias library='printf ".ezproxy.lib.monash.edu.au" | pbcopy'
alias mkdir='mkdir -pv'
alias mv='mv -i'
alias myip='dig +short myip.opendns.com @resolver1.opendns.com'
alias pgrep='pgrep -a -l'
alias pprint='print_hashed_path'
alias rg='rg -S'
alias scp='scp -r'
alias ssh='ssh -Y'
alias sudo='sudo '
alias type='type -a'
alias vimrc='vim ~/repos/dotfiles/vim/nvim/init.vim'
alias which='which -a'

# Print shell variable separated by new line.
alias fpath='print -l $fpath'
alias ldpath='print -l $dyld_library_path'
alias path='print -l $path'

# Use trash not rm.
if (( $+commands[trash] )); then
  alias bin=trash
  alias rm='printf \
    "Use '\''bin'\'' instead, or '\''\\\rm'\'' for real rm if required.\n\c"'
else
  alias rm='rm -R'
fi

# Change directory.
alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'
alias -g ......='../../../../..'
alias -- -='cd -'
alias 1='cd -'
alias 2='cd -2'
alias 3='cd -3'
alias 4='cd -4'
alias 5='cd -5'
alias 6='cd -6'
alias 7='cd -7'
alias 8='cd -8'
alias 9='cd -9'

# List directory contents.
if (( $+commands[exa] )); then
  alias l='exa --long --header'
  alias ls='exa --oneline'
  alias la='exa --long --header --sort=accessed --time=accessed'
  alias lc='exa --long --header --sort=created --time=created'
  alias le='exa --long --header --extended'
  alias lg='exa --long --header --git'
  alias lh='exa --long --header --all'
  alias ll='exa --long --header --all'
  alias lm='exa --long --header --sort=modified --time=modified'
  alias lr='exa --long --header --recurse'
  alias lt='exa --long --header --tree'
  alias lx='exa --long --header --sort=extension'
  alias lz='exa --long --header --sort=size'
  alias tree='exa --tree'
else
  if [[ "$OSTYPE" == darwin* ]]; then
    alias ls='ls -G -1'
  else
    alias ls='ls --color=tty -1'
  fi
  alias l='ls -lh'
  alias la='ls -lah'
  alias ll='ls -lAh'
  alias lx='ls -lAh -XB'  # Extension
  alias lk='ls -lAh -Sr'  # File size
  alias lt='ls -lAh -tur' # Access time
  alias lc='ls -lAh -tcr' # File change time
  alias lm='ls -lAh -tr'  # Modification time
fi

# Git.
alias ga='git add'
alias gam='git add --update'
alias gap='git add --patch'
alias gc='git commit --verbose'
alias gcl='git clean --force'
alias gcm='git commit --message'
alias gco='git checkout'
alias gd='git diff'
alias gds='git diff --staged'
alias gl='git pull'
alias glg='git log --stat --abbrev-commit'
alias glgc='git-log-compact'
alias glgg='git log --graph --abbrev-commit'
alias glgo='git log --oneline --abbrev-commit'
alias glgp='git log --patch --abbrev-commit'
alias gp='git push'
alias gsh='git show'
alias gsp='git status --porcelain'
alias gst='git status'

# Tmux.
alias ta='tmux attach'
alias tl='tmux list-sessions'
alias tk='tmux kill-session'
alias tn='tmux new-session'

# Neovim.
if (( $+commands[nvim] )); then
  alias vim=nvim
  alias ex='nvim -e'
  alias view='nvim -R'
  alias vimdiff='nvim -d'
fi

# Resize terminal window.
alias tiny="printf '\e[8;45;85t'"
alias small="printf '\e[8;60;100t'"
alias medium="printf '\e[8;60;150t'"
alias large="printf '\e[8;60;200t'"

# macOS specific.
if [[ "$OSTYPE" == darwin* ]]; then

  # Clipboard copy/paste.
  alias copy='pbcopy'
  alias paste='pbpaste'

  # Homebrew.
  alias update='brew update && brew upgrade && yes | brew cleanup'

  # Conda Python.
  _ipython () {
    $CONDA_PREFIX/bin/pythonw $CONDA_PREFIX/bin/ipython
  }
  alias ipython=_ipython

# Linux specific.
else

  # Like pbcopy and pbpaste on Linux systems.
  alias copy='xsel --clipboard --input'
  alias paste='xsel --clipboard --output'

  # Open app from command line.
  alias open=xdg-open

  # Say out loud.
  alias say=spd-say

  # APT.
  if uname -a | grep -i ubuntu >/dev/null; then
    alias update="sudo apt update && sudo apt -y upgrade"
  fi

fi
