#         _               _
#        | |             | |
#        | |__   __ _ ___| |__  _ __ ___
#        | '_ \ / _` / __| '_ \| '__/ __|
#       _| |_) | (_| \__ \ | | | | | (__
#      (_)_.__/ \__,_|___/_| |_|_|  \___|

# Settings mostly derived from Sensible Bash
# https://github.com/mrzool/bash-sensible

# Check bash version
((BASH_VERSINFO[0] < 4)) &&
  echo "Bash version is < 4.0, some options will not work correctly."

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

## ALIASES ##

# Copy recursively and interactively
alias cp='cp -i -r'

# Directory listing
alias l='ls -lh'
alias ll='ls -lah'
alias lm='ls -lahtr'
alias ls='ls -1'

# Make directories with parents
alias mkdir='mkdir -pv'

# Move interactively
alias mv='mv -i'

# Copy recursively over ssh
alias scp='scp -r'

# Remove recursively and interactively
alias rm='rm -I -R'

# Display all matches for which
alias which='which -a'

## GENERAL OPTIONS ##

# Prevent file overwrite on stdout redirection
# Use `>|` to force redirection to an existing file
set -o noclobber

# Automatically trim long paths in the prompt
PROMPT_DIRTRIM=2

# Turn on recursive globbing (enables ** to recurse all directories)
shopt -s globstar 2> /dev/null

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob;

## TAB-COMPLETION ##

# Perform file completion in a case insensitive fashion
bind "set completion-ignore-case on"

# Treat hyphens and underscores as equivalent
bind "set completion-map-case on"

# Display matches for ambiguous patterns at first tab press
bind "set show-all-if-ambiguous on"

# Immediately add a trailing slash when autocompleting symlinks to directories
bind "set mark-symlinked-directories on"

## HISTORY ##

# Append to the history file, don't overwrite it
shopt -s histappend

# Save multi-line commands as one command
shopt -s cmdhist

# Record each line as it gets issued
PROMPT_COMMAND='history -a'

# Huge history.
HISTSIZE=500000
HISTFILESIZE=100000

# Avoid duplicate entries
HISTCONTROL="erasedups:ignoreboth"

# Don't record some commands
export HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history:clear"

# Use standard ISO 8601 timestamp
# %F equivalent to %Y-%m-%d
# %T equivalent to %H:%M:%S (24-hours format)
HISTTIMEFORMAT='%F %T '

# Enable incremental history search with up/down arrows
bind '"\C-p": history-search-backward'
bind '"\C-n": history-search-forward'
bind '"\e[C": forward-char'
bind '"\e[D": backward-char'

## DIRECTORY NAVIGATION ##

# Prepend cd to directory names automatically
shopt -s autocd 2> /dev/null
# Correct spelling errors during tab-completion
shopt -s dirspell 2> /dev/null
# Correct spelling errors in arguments supplied to cd
shopt -s cdspell 2> /dev/null

# This defines where cd looks for targets
# Add the directories you want to have fast access to, separated by colon
# Ex: CDPATH=".:~:~/projects" will look for targets in the current working
# directory, in home and in the ~/projects folder
CDPATH="."

# This allows you to bookmark your favorite places across the file system
# Define a variable containing a path and you will be able to cd into it
# regardless of the directory you're in
shopt -s cdable_vars

# Example:
export repos="$HOME/repos"
