format = """\
    $conda\
    $nodejs\
    $python\
    $rust\
    $nix_shell\
    $hostname\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $cmd_duration\
    $line_break\
    $jobs\
    $character\
    """

[cmd_duration]
format = " [⤳ $duration](bold 242) "

[conda]
format = "[$symbol$environment ]($style)[•](242) "
ignore_base = false

[directory]
format = "[$path ]($style)[$read_only ]($read_only_style)[•](242) "

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold yellow"

[git_commit]
style = "bold yellow"

[git_state]
style = "bold yellow"

[git_status]
style = "bold yellow"

[hostname]
format = "[$hostname ]($style)[•](242) "
ssh_only = false
style = "bold red"

[nix_shell]
disabled = false
format = '[$state( \($name\)) ]($style)[•](242) '
style = "bold blue"

[nodejs]
format = "[$symbol$version ]($style)[•](242) "
style = "bold green"
symbol = "⬢ "

[python]
format = '[$symbol${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)[•](242) '
style = "bold green"
symbol = '∏ '

[rust]
format = "[$symbol($version )]($style)[•](242) "
style = "bold green"
