format = """\
    $time\
    [$hostname]("bold blue")\
    in $directory\
    $git_branch\
    $git_state\
    $git_status\
    $conda\
    $env_var\
    $cmd_duration\
    $line_break\
    $jobs\
    $battery\
    $character\
    """

[conda]
symbol = "🅒 "
ignore_base = false

[time]
disabled = false
