format = """\
    $conda\
    $nix_shell\
    $hostname\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $cmd_duration\
    $line_break\
    $jobs\
    $character\
    """

[cmd_duration]
format = " [⤳ $duration](bold #f3ad10) "

[conda]
format = "[$symbol$environment]($style) [•](242) "
ignore_base = false

[directory]
format = "[$path]($style)[$read_only]($read_only_style) [•](242) "

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold #f3ad10"

[git_commit]
style = "bold #f3ad10"

[git_state]
style = "bold #f3ad10"

[git_status]
style = "bold #f3ad10"

[hostname]
format = "[$hostname]($style) [•](242) "
ssh_only = false
style = "bold red"

[nix_shell]
disabled = false
format = '[$state( \($name\))](bold blue) [•](242) '
