format = """\
    $conda\
    $hostname\
    $directory\
    $git_branch\
    $git_state\
    $git_status\
    $cmd_duration\
    $line_break\
    $jobs\
    $character\
    """

[cmd_duration]
format = " [⤳ $duration](bold #f3ad10) "

[conda]
format = "[$symbol$environment]($style) [•](242) "
ignore_base = false

[git_branch]
format = "[•](242) [$symbol$branch]($style) "

[hostname]
format = "[$hostname]($style) [•](242) "
ssh_only = false
style = "bold red"
