bat
bib-tool
colordiff
coreutils
dos2unix
exa
brew install bellecp/fast-p/fast-pdf-finder
fd
ffmpeg
fzf
gawk
gcc --without-multilib
git
git-lfs
htop
hyperfine
imagemagick
iperf
ispell
jq
mas
parallel
poppler
pv
ranger
ripgrep
shellcheck
the_silver_searcher
tmux
trash
tree
--HEAD universal-ctags/universal-ctags/universal-ctags
watch
wget
