#!/usr/bin/env python3
"""Install software."""

from pathlib import Path
from shutil import which
from subprocess import CalledProcessError, run
from sys import platform

# TODO: add argparse and options for installing.
# TODO: is it possible to write tests for this?

BOLD = "\033[1m"
RESET = "\033[0m"
RED = "\033[1;31m"
GREEN = "\033[1;32m"
YELLOW = "\033[1;33m"
GREY = "\033[1;90m"

TICK = f"{GREEN}\u2713{RESET}"
CROSS = f"{RED}\u2718{RESET}"
ARROW = f"{YELLOW}\u27BE{RESET}"

INSTALL_DIR = Path(__file__).parent.parent / "install"


# ------------------------------------------------------------------------------------ #
# Utility


def header(msg):
    print(f"\n{BOLD}{GREY}=== {msg.upper()} ==={RESET}\n")


def printer(msg, status):
    print(f"{status}  {BOLD}{GREY}{msg}{RESET}")


def read_lines(file):
    with open(file, "r") as fp:
        return [line.strip() for line in fp.readlines()]


def linux_distro():
    try:
        output = run(["lsb_release", "-is"], capture_output=True)
    except FileNotFoundError:
        return ""
    return output.stdout.decode().lower().strip()


def is_installed(app):
    if which(app) is None:
        return False
    return True


def get_system():
    if platform == "darwin":
        return "macos"
    elif platform == "linux":
        ld = linux_distro()
        if ld in ["fedora", "ubuntu"]:
            return ld
    raise RuntimeError("unsupported platform")


def install_with_helper(file, command):
    pkgs = read_lines(file)
    for pkg in pkgs:
        try:
            run(f"{command} {pkg}".split(" "), check=True)
        except CalledProcessError:
            printer(msg=f"failed to install {pkg}", status=CROSS)
        else:
            printer(msg=f"installed {pkg}", status=TICK)


# ------------------------------------------------------------------------------------ #
# Install with


def install_with_apt():
    install_with_helper(file=INSTALL_DIR / "pkglist.txt", command="sudo apt install -y")


def install_with_brew():
    run(["brew", "bundle", "--file", INSTALL_DIR / "Brewfile"], check=True)


def install_with_code():
    install_with_helper(
        file=INSTALL_DIR / "extensions.txt", command="code --install-extension"
    )


def install_with_dnf():
    install_with_helper(file=INSTALL_DIR / "pkglist.txt", command="sudo dnf install -y")


# ------------------------------------------------------------------------------------ #
# Install app


def install_brew():
    run(
        [
            "/usr/bin/ruby",
            "-e",
            "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)",
        ],
        check=True,
    )
    run(["brew", "update"], check=True)
    run(["brew", "doctor"], check=True)


def install_fzf():
    path = Path("~/.fzf").expanduser()
    run(
        [
            "git",
            "clone",
            "--depth",
            "1",
            "https://github.com/junegunn/fzf.git",
            path,
        ],
        check=True,
    )
    run([path / "install"], check=True)


def install_starship():
    path = Path("~/bin").expanduser()
    if not path.exists():
        path.mkdir()
    TMPFILE = Path("tmp.sh")
    with open(TMPFILE, "w") as fp:
        run(["curl", "-fsSL", "https://starship.rs/install.sh"], stdout=fp, check=True)
    run(["chmod", "+x", TMPFILE], check=True)
    run(["bash", TMPFILE, "--yes", f"--bin-dir={path}"], check=True)
    TMPFILE.unlink()


def install_vim_plug():
    # Neovim (nvim)
    path = Path("~/.local/share/nvim/site/autoload/plug.vim").expanduser()
    run(
        [
            "sh",
            "-c",
            f"curl -fLo {path} "
            "--create-dirs "
            "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim",
        ],
        check=True,
    )
    # Vim
    path = Path("~/.vim/autoload/plug.vim").expanduser()
    Path("~/.vim/swp").expanduser().mkdir(parents=True, exist_ok=True)
    Path("~/.vim/undo").expanduser().mkdir(parents=True, exist_ok=True)
    run(
        [
            "curl",
            "-fLo",
            path,
            "--create-dirs",
            "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim",
        ],
        check=True,
    )


# ------------------------------------------------------------------------------------ #

SYSTEM = get_system()

APPS = dict(
    macos=["brew", "fzf", "starship", "vim_plug"],
    fedora=["fzf", "starship", "vim_plug"],
    ubuntu=["fzf", "starship", "vim_plug"],
)

INSTALLERS = dict(
    macos=["brew", "code"],
    fedora=["code", "dnf"],
    ubuntu=["apt", "code"],
)

INSTALL_APP = dict(
    brew=install_brew,
    fzf=install_fzf,
    starship=install_starship,
    vim_plug=install_vim_plug,
)

INSTALL_WITH = dict(
    apt=install_with_apt,
    brew=install_with_brew,
    code=install_with_code,
    dnf=install_with_dnf,
)

# ------------------------------------------------------------------------------------ #


def install_app(app):
    INSTALL_APP[app]()


def install_with(installer):
    INSTALL_WITH[installer]()


def main():
    apps = APPS[SYSTEM]
    installers = INSTALLERS[SYSTEM]

    header("installing with package managers")
    for installer in installers:
        if is_installed(installer):
            printer(msg=f"installing with {installer}", status=ARROW)
            install_with(installer)
        else:
            printer(msg=f"{installer} not available, skipping", status=CROSS)

    header("installing other apps")
    for app in apps:
        if not is_installed(app):
            printer(msg=f"installing {app}", status=ARROW)
            try:
                install_app(app)
            except CalledProcessError:
                printer(msg=f"failed to install {app}", status=CROSS)
            else:
                printer(msg=f"installed {app}", status=TICK)
        else:
            printer(msg=f"{app} already installed", status=TICK)


if __name__ == "__main__":
    main()
