#!/usr/bin/env python3
"""Install software."""

from pathlib import Path
from subprocess import run
from sys import platform

# TODO: add argparse and options for installing.
# TODO: is it possible to write tests for this?

BOLD = "\033[1m"
RESET = "\033[0m"
RED = "\033[1;31m"
GREEN = "\033[1;32m"
YELLOW = "\033[1;33m"
GREY = "\033[1;90m"

TICK = f"{GREEN}\u2713{RESET}"
CROSS = f"{RED}\u2718{RESET}"
ARROW = f"{YELLOW}\u27BE{RESET}"

INSTALL_DIR = Path(__file__).parent.parent / "install"


def printer(msg, status):
    print(f"{status}  {BOLD}{GREY}{msg}{RESET}")


def is_linux_distro(distro):
    try:
        output = run(["lsb_release", "-is"], capture_output=True)
    except FileNotFoundError:
        return False
    if output.stdout.decode().lower() == distro.lower():
        return True
    return False


def is_installed(app):
    if run(["command", "-v", app], capture_output=True).returncode == 0:
        return True
    return False


def read_lines(file):
    with open(file, "r") as fp:
        return [line.strip() for line in fp.readlines()]


def install_with_apt():
    pkgs = read_lines(INSTALL_DIR / "pkglist.txt")
    for pkg in pkgs:
        run(["sudo", "apt", "install", "-y", pkg])


def install_with_brew():
    run(["brew", "bundle", "--file", INSTALL_DIR / "Brewfile"])


def install_with_code():
    exts = read_lines(INSTALL_DIR / "extensions.txt")
    for ext in exts:
        run(["code", "--install-extension", ext])


def install_with_dnf():
    pkgs = read_lines(INSTALL_DIR / "pkglist.txt")
    for pkg in pkgs:
        run(["sudo", "dnf", "install", "-y", pkg])


def install_with_nvim():
    path = Path("~/.local/share/nvim/site/autoload/plug.vim").expanduser()
    run(
        [
            "sh",
            "-c",
            f"'curl -fLo {path} "
            "--create-dirs "
            "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'",
        ]
    )
    run(["nvim", "+PlugInstall", "+qall"])


def install_with_vim():
    Path("~/.vim/swp").expanduser().mkdir(parents=True, exist_ok=True)
    Path("~/.vim/undo").expanduser().mkdir(parents=True, exist_ok=True)
    path = Path("~/.vim/autoload/plug.vim").expanduser()
    run(
        [
            "curl",
            "-fLo",
            path,
            "--create-dirs",
            "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim",
        ]
    )
    run(["vim", "+PlugInstall", "+qall"])


def install_brew():
    run(
        [
            "/usr/bin/ruby",
            "-e",
            "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)",
        ]
    )
    run(["brew", "update"])
    run(["brew", "doctor"])


def install_fzf():
    path = Path("~/.fzf").expanduser()
    run(
        [
            "git",
            "clone",
            "--depth",
            "1",
            "https://github.com/junegunn/fzf.git",
            path,
        ]
    )
    run([path / "install"])


def install_starship():
    path = Path("~/bin").expanduser()
    if not path.exists():
        path.mkdir()
    TMPFILE = Path("tmp.sh")
    with open(TMPFILE, "w") as fp:
        run(["curl", "-fsSL", "https://starship.rs/install.sh"], stdout=fp)
    run(["chmod", "+x", TMPFILE])
    run(["bash", TMPFILE, "--yes", f"--bin-dir={path}"])
    TMPFILE.unlink()


def configure_macos():
    run(["bash", INSTALL_DIR / "mac.sh"])


def get_system():
    if platform == "darwin":
        return "macos"
    elif platform == "linux":
        if is_linux_distro("Ubuntu"):
            return "ubuntu"
        if is_linux_distro("Fedora"):
            return "fedora"
    else:
        raise RuntimeError("unsupported platform")


SYSTEM = get_system()

APPS = dict(
    macos=["brew", "fzf", "starship"],
    fedora=["fzf", "starship"],
    ubuntu=["fzf", "starship"],
)

INSTALLERS = dict(
    macos=["brew", "code"],
    fedora=["code", "dnf"],
    ubuntu=["apt", "code"],
)

CONFIGURE = dict(
    macos=configure_macos,
)

INSTALL_APP = dict(
    brew=install_brew,
    fzf=install_fzf,
    starship=install_starship,
)

INSTALL_WITH = dict(
    apt=install_with_apt,
    brew=install_with_brew,
    code=install_with_code,
    dnf=install_with_dnf,
    nvim=install_with_nvim,
    vim=install_with_vim,
)


def main():
    apps = APPS[SYSTEM]
    installers = INSTALLERS[SYSTEM]
    configure = CONFIGURE[SYSTEM]

    for app in apps:
        if not is_installed(app):
            printer(msg=f"installing {app}", status=ARROW)
            INSTALL_APP[app]()
            printer(msg=f"installed {app}", status=TICK)
        else:
            printer(msg=f"{app} already installed", status=TICK)

    for installer in installers:
        if is_installed(installer):
            printer(msg=f"installing with {installer}", status=ARROW)
            INSTALL_WITH[installer]()
            printer(msg=f"installed with {installer}", status=TICK)
        else:
            printer(msg=f"{installer} not available, skipping", status=CROSS)

    configure()


if __name__ == "__main__":
    main()
