#!/usr/bin/env zsh

# ==== plugins ==== #

fpath=("$HOME/.local/share/zsh/functions" $fpath)

# Autosuggestions.
source ~/.local/share/zsh/repos/zsh-autosuggestions/zsh-autosuggestions.zsh
bindkey '^ ' autosuggest-accept	            # Key binding: Ctrl-Space.
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=240'    # Color.

# Syntax-hightlighting.
source ~/.local/share/zsh/repos/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Extra completions.
fpath=(~/.local/share/zsh/repos/zsh-completions $fpath)
fpath=(~/.local/share/zsh/repos/conda-zsh-completion $fpath)
compinit conda
